# Generated by Django 2.2.9 on 2020-02-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.TextField(default='caption', max_length=30),
            preserve_default=False,
        ),
    ]
